### ISSUE TITLE
Onderzoeken Django apps

### ISSUE THREAD

**Issue by BvdG-HAN** [MirrorBoys/TheMirror#131]
Het is bij ons allen nog niet helemaal duidelijk wanneer je een app binnen Django dient te maken. In dit issue doen we hier kort onderzoek naar en formuleren we een lijst met apps voor ons project.

**Comment by Thorsten3** [comment]
Informatie:
Apps worden gebruikt om een onderscheidt te maken tussen duidelijk verschillende functionaliteit.
één app kan dus gezien worden als een subonderdeel van een Django project

Bijvoorbeeld een project is een website en er zijn verschillende apps voor de home pagina en een betaal pagina.

Communicatie tussen apps is mogelijk doormiddel van public classes en accessor methods

**Comment by Thorsten3** [comment]
Met deze informatie zou ik verwachten dat de mogelijke apps gaan zijn:

- Smartmirror voor de webpagina van de mirror
- configuratie 
De situatie met camera en nfc is lastiger want dat kan op drie verschillende manieren: 
1. 
- NFC
- Camera

2 .
- Authenticatie 
- Gestures

3.
- Samen 

Mijn voorkeur zou uitgaan naar authenticatie en gestures aangezien dat de functionaliteit is en de camera en NFC die middelen zijn hoe we het gaan bereiken

**Comment by briandreuning** [comment]
Heb hier naar gekeken, makes sense, duidelijk.
