### ISSUE TITLE
Configureren webserver zodat we zonder subpad op de thuispagina terecht komen

### ISSUE THREAD

**Issue by BvdG-HAN** [MirrorBoys/TheMirror#143]
### The improvement

Op dit moment moeten we navigeren naar http://localhost:8000/TheMirror om op de thuispagina te komen. Het zou mooi zijn als we vanuit http://localhost:8000 direct op de homepagina komen.

**Comment by Thorsten3** [comment]
Waarom zouden we dan niet gelijk poort 80 doen. Dan hoef je ook geen poortnummer erachter te zetten

**Comment by Thorsten3** [comment]
Gekeken naar de server draaien op poort 80. Binnen Django is dit goed te doen alleen wsl laat het niet toe. Dit in combinatie met het feit dat op de raspberry pi de webserver toch automatisch wordt opgestart waardoor het poortnummer niet ingevoerd hoeft te worden heeft ervoor gezorgd dat er is besloten om hier niet verder naar te kijken.
