### ISSUE TITLE
Configureren ontwikkelomgeving i.c.m. Raspberry Pi

### ISSUE THREAD

**Issue by BvdG-HAN** [MirrorBoys/TheMirror#49]
### The task

Ontwikkelomgeving zo configureren dat we kunnen ontwikkelen op/voor de Raspberry Pi. Dit is noodzakelijk voor het testen/configureren van de hardware zoals de NFC-reader en camera

**Comment by Thorsten3** [comment]
[Opzetten ontwikkelomgeving rpi.txt](https://github.com/user-attachments/files/17649491/Opzetten.ontwikkelomgeving.rpi.txt)
